### ISSUE TITLE
add binary releases

### ISSUE THREAD

**Issue by gyreas** [falbru/kakoune-qt#80]
For those wanting to quickly decide if this is for them, a binary to download is much more convenient and accessible than setting up C++ toolchain to build the project from source (which can come after the decide to switch).

It'd be helpful to add the binary for common arch/OS to the github release view

**Comment by falbru** [comment]
@gyreas Thank you for your feedback!

I 100% agree with you! I'll be adding some binary releases ASAP!

**Comment by falbru** [comment]
Solved with [release v0.1!](https://github.com/falbru/kakoune-qt/releases/tag/v0.1)
